apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: scorepubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: "localhost:6379"
  - name: redisPassword
    value: ""
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kvstore
spec:
  type: state.in-memory
  version: v1
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: userscores
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: "localhost:6379"
  - name: redisPassword
    value: ""
  - name: queryIndexes
    value: |
      [
        {
          "name": "leaderboardIndex",
          "indexes": [
            {
              "key": "password",
              "type": "TEXT"
            },
            {
              "key": "wins",
              "type": "NUMERIC"
            },
            {
              "key": "points",
              "type": "NUMERIC"
            },
            {
              "key": "games",
              "type": "NUMERIC"
            },
            {
              "key": "type",
              "type": "TEXT"
            }
          ]
        }
      ]
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: scoreupdate
spec:
  topic: 'scoreupdates'
  routes:
    default: '/update-score'
  pubsubname: scorepubsub
